### ISSUE TITLE
next time this course is run?

### ISSUE THREAD

**Issue by cjcjameson** [monte-carlo-data/data-downtime-challenge#11]
@RyanOthnielKearns let me know next time this course is being run, I might be interested!

**Comment by RyanOthnielKearns** [comment]
@cjcjameson absolutely! Currently it's a bit ad hoc with the flow of conferences / other events where we get to showcase the material. But I will try to remember to let you know next time! :) MC socials and other comms should mention it next time we have a course scheduled.
